classDiagram 
    class Loan {
        - id
        - book
        - user
        - dueData
        - returnDate
        - loanDate
        + loan(book, user, dueDate, returnDate, loanDate)
        + renew(newDueDate)
        + return()
        + isOverDue()
    }

    class Notification {
        <<interface>>
        + notify(loan)
    }

    class EmailNotifier {
        + notify(loan)
    }
    class EmailService{
        + send(message)
    }

    Loan --> Notification : usa
    EmailNotifier .. |> Notification : implementa